name: manage-azure-policy-23eea0d9
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Test_SQL_Redundancy_81094617-2338-4572-aa13-66d39be71aeb/**'
#      - .github/workflows/manage-azure-policy-23eea0d9.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_23eea0d9}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Test_SQL_Redundancy_81094617-2338-4572-aa13-66d39be71aeb/**
